Feature/associations
Felipe-Perez-Ferraro/ruby-school-library pull request #5
Opened 2023-10-10 20:42 UTC by Felipe-Perez-Ferraro

- Created the Book class
- Created the Classroom class
- Created the Rental class
- Added the rental array in the constructor
- Added classroom in the constructor
- Tested the code

2023-10-10 21:40 UTC, skyv26 requested changes
## Hi @Felipe-Perez-Ferraro, 

Good job so far 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNjVhZjBiZjUzZmYxZjI1NGFhNGQ0ZjIyN2FhOTcwNDZlZmUzNmZkMiZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/L422JoNlBBBD42zkQ9/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Professional `README` template ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-10 21:40 UTC, skyv26 commented on student.rb
- [ ] Please 🙏🏻 adhere to the requirements, you did a great job so far and it seems like you missed a requirement, which is tricky but very important to understand, as per requirements you added the students to the `classroom` because a student has many classrooms, but the opposite scenarios are also true and very very important according to which a `classroom` can be used by many `students`. So it is a two-way association. Kindly add the associations by adding the classroom setter for the `student` class. I have attached the requirement screenshot and also added the hint for you to add the association properly.

### Requirement
![image](https://github.com/Felipe-Perez-Ferraro/ruby-school-library/assets/66476329/1207e753-c582-4bc7-8000-1e5068b84e06)

### Hint
```ruby
class Student < Person
  attr_reader :classroom
  .
  .
  def classroom=(classroom)
      @classroom = classroom
      classroom.students.push(self) unless classroom.students.include?(self)
  end
end
```

2023-10-10 21:40 UTC, skyv26 commented on book.rb
- [ ] As I mentioned it is very important to understand the association at this point and without setting up the association properly you will not get the desired result. In this `book` class, you need to understand that `rental` acts as the `intermediate` class between the book and the `student` because in order to make the student able to rent a book, we need to establish a relation between each of them. Please take a look at the below hint.

### Hint

```ruby
class Book
  # *Getters and Setters for @rentals should be present
  attr_accessor :title, :author, :rentals
  .
  .

  def initialize(title, author)
    .
    .
    @rentals = []
  end
  
  def add_rental(person, date)
    Rental.new(date, self, person)
  end
end

```

2023-10-10 21:40 UTC, skyv26 commented on rental.rb
> +  attr_reader :person, :book
- [ ] Please make your properties both `read` and `write` because you are using both of them to add the rentals associated between them. Making your properties read-only will give undesired result when you will add the data.

2023-10-10 21:40 UTC, skyv26 commented on person.rb
- [ ] Well no doubt, you made great progress but I can see that you are struggling with the `association`, but don't worry take your time to understand because it will be very important for the ruby on rails. As I mentioned already related to `rentals` which is an intermediate between the person and `book`. You need to put the `setter` method for the `rentals` in order to establish an association successfully, when you create a rental, your output will be different.

### Hint


```ruby
class Person
  # *Getters and Setters for @rentals should be present
  attr_accessor :name, :age, :rentals
  .
  .

  def initialize(age, name = "Unknown", parent_permission = true)
    .
    .
    @rentals = []
  end

  def add_rental(book, date)
    # *The person itself should be sent as a parameter to create the new rental achieving the 'has-many' association
    Rental.new(date, book, self)
  end

  .
  .
end

```

2023-10-11 17:25 UTC, VICTOR-CHUKWU approved these changes
Hi @Felipe-Perez-Ferraro , 
# STATUS: APPROVED! 🥇 💯 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-11 20:08 UTC, merged